<?php defined('BASEPATH') OR exit('No direct script access allowed');
//DO NOT EDIT THIS FILE

//ClassMap for autoloader 
 
$classes = array (
	'FS' => APPPATH.'core/FS.php', 
	'Emodelo' => APPPATH.'models/Emodelo.php',
	'Common' => APPPATH.'models/Common.php',
	'Translate' => APPPATH.'models/Translate.php',
	'TFA' => APPPATH.'libraries/TFA.php',
 	'Avatar' => APPPATH.'libraries/Avatar.php',
	);